### ISSUE TITLE
USER STORY: New User Registration

### ISSUE THREAD

**Issue by Noah-Samawi** [Noah-Samawi/pp4-Web-Application-Security#11]
As a Site User I can register an account so that I can add/edit/delete my SecurityFeatures and comment on and bookmark other people's SecurityFeatures and add SecurityFeatures to my techsecurityplanner.

## Acceptance Criteria:
- **Acceptance Criteria 1**: A signup button should be visible on the homepage.
- **Acceptance Criteria 2**: When I click the button I should be taken to the signup page.
- **Acceptance Criteria 3**: When I fill in my details and click submit a new account should be created for me.
- **Acceptance Criteria 4**: I should then be notified that I have been logged in.

## Tasks:

- [x] Install allauth and add to installed apps.
- [x] Add allauth URLs to the project.
- [x] Add signup link to navbar and home page
- [x] Customise allauth signup form HTML templates
- [x] Create message to notify user of successful signup

**Comment by Noah-Samawi** [comment]
Update #12 USER STORY: New User Registration
