### ISSUE TITLE
USER STORY: Admin SecurityFearure Management

### ISSUE THREAD

**Issue by Noah-Samawi** [Noah-Samawi/pp4-Web-Application-Security#13]
As a Site Administrator, I can create, read, update, and delete SecurityFeatures, comments, and TechSecurity plans so that I can manage the app content.

## Acceptance Criteria
- **Acceptance Criteria 1**: When the admin user is logged into the admin panel, they can see a list of all SecurityFeatures, comments, and TechSecurity plan items.
- **Acceptance Criteria 2**: The admin user can delete and edit any SecurityFeature, comment, or TechSecurity plan item across the site.
- **Acceptance Criteria 3**: TAcceptance Criteria 3: The admin user can create new SecurityFeatures, comments, and TechSecurity plan items.

## Tasks

- [x] Create SecurityFeature, Comment, and TechSecurity plan item models to include all required fields.
- [x]  Create a superuser
- [x]  Set up SecurityFeature, Comment, and TechSecurity Plan Item models on the admin site.
- [x]  Install Summernote for creating SecurityFeatures.

**Comment by Noah-Samawi** [comment]
Admin capabilities: Create, read, update, and delete SecurityFeatures, comments, and TechSecurity plans. Set up models and admin site.
