### ISSUE TITLE
USER STORY: View My SecurityFeature

### ISSUE THREAD

**Issue by Noah-Samawi** [Noah-Samawi/pp4-Web-Application-Security#2]
As a Site User, I can view my security features so that I can view and manage all security features I have created in one location.

## Acceptance Criteria
- **Acceptance Criteria 1**: When the user is logged in, a 'My SecurityFeatures' button should appear in the navbar.
- **Acceptance Criteria 2**: When the user clicks the button, they should be taken to the 'My Security Features' page.
- **Acceptance Criteria 3**: The 'My Security Features' page should show a list of security features that the user is the author of (both draft and published).
- **Acceptance Criteria 4**: The individual security features should appear as cards showing the security feature image, title, and search time.
- **Acceptance Criteria 1**: Acceptance Criteria 5: When the user clicks on an individual security feature, they are taken to the full security feature details.

## Tasks:
- [x] Create HTML template for 'My Security Features'.
- [x]  Develop a user-friendly security feature card layout using Bootstrap cards and make it responsive.
- [x]  Create a view for 'My Security Features' using Django ListView and filter security features where the author is the logged-in user.
- [x]  Create a button for 'My Security Features' on the navbar, which only displays when the user is logged in.
