### ISSUE TITLE
 USER STORY: View TechSecurithy

### ISSUE THREAD

**Issue by Noah-Samawi** [Noah-Samawi/pp4-Web-Application-Security#6]
As a Site User, I can view my TechSecurithy plan for the week when I log into my account so that I can plan for the week ahead.

## Acceptance Criteria:
- **Acceptance Criteria 1**:  A TechSecurithy plan button should appear in the navbar when the user is logged in.
- **Acceptance Criteria 2**:  When the user clicks on the button they should be taken to the TechSecurithy plan page.
- **Acceptance Criteria 3**:  The page should display a SecurityFeature card for each day of the week.
- **Acceptance Criteria 4**:  If a TechSecurithy plan item has been added to a day, the card should display the SecurityFeature image and title. When the user clicks on the card they should be taken to the SecurityFeature detail.
- **Acceptance Criteria 5**:  If the day has no TechSecurithy plan item allocated, the card should display a plus symbol and 'Add SecurityFeature'. When the user clicks on the card they should be taken to the browse SecurityFeature page.

## Tasks:
- [x] Create TechSecurithyPlan class in views.py to filter TechSecurithyPlanItems by logged in user and create dictionary to display Day and TechSecurithyplanItem.
- [x] Create TechSecurithy Plan HTML template.
- [x] Display TechSecurithy plan items in a user friendly format using bootstrap cards.
- [x] Add links to cards to take user to SecurityFeature detail page or browse SecurityFeature page.
- [x] Create button on Nav bar for TechSecurithy Plan and only display if user is logged in.

**Comment by Noah-Samawi** [comment]
Update #6
