### ISSUE TITLE
USER STORY: View Bookmarked SecurityFeatures

### ISSUE THREAD

**Issue by Noah-Samawi** [Noah-Samawi/pp4-Web-Application-Security#8]
As a Site User I can view my bookmarked SecurityFeatures so I can find them easily in the one location.

## Acceptance Criteria:
- **Acceptance Criteria 1**: When the user is logged in, a 'My Bookmarks' button should appear in the navbar.
- **Acceptance Criteria 2**: When the user clicks the button they should be taken to the 'My Bookmarks' page.
- **Acceptance Criteria 3**: The 'My Bookmarks' page should show a list of SecurityFeatures that the user has added to their bookmarks.
- **Acceptance Criteria 4**: The individual SecurityFeature should appear as cards showing the SecurityFeature image, title and search time.
- **Acceptance Criteria 5**: When the user clicks on an individual SecurityFeatures they are taken to the full SecurityFeatures details.

## Tasks:

 - [x] Create HTML template for my Bookmarked SecurityFeature.
 - [x] Develop a user-friendly SecurityFeature card layout using bootstrap cards and make it responsive.
 - [x] Create View for MyBookmarks using Django Listview and filter all SecurityFeature by favourites that include the user ID.
 - [x] Create a button for Bookmarked SecurityFeature on the Navbar which only displays when the user is logged in.

**Comment by Noah-Samawi** [comment]
Update #8
